# Generated by Django 4.0.5 on 2022-06-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('host', models.CharField(max_length=12, unique=True)),
                ('guest_can_edit', models.BooleanField(default=False)),
                ('guest_can_upload_files_amount', models.IntegerField(default=2)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
