# Generated by Django 4.0.5 on 2022-07-03 00:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='textediton',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generate_code, max_length=8, unique=True),
        ),
    ]
